---
title: "About this site"
description: |
  Is this your... third blog now?
output: 
  distill::distill_article:
    md_extensions: +emoji
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Charlotte Hadley

Hey! I'm Charlie ([she/her](https://pronoun.is/she)) and have been teaching and consulting with R and Shiny since 2016.

- I co-run the awesome [R in 3 Months](https://rfortherestofus.com/3months/) programme at [R for the Rest of Us](https://rfortherestofus.com/).

- I have 5 courses about R available on [LinkedIn Learning](https://www.linkedin.com/learning/instructors/charlie-joey-hadley?u=2125562)

- I'm very proud of this [Mapping with R](https://rfortherestofus.com/courses/mapping/) course which is designed for folks without mapping or GIS experience.

As well as these things, I'm a trans and LGBT rights activist :rainbow_flag:. All tech is political. Black Lives Matter.


# What's this blog for?

I've had several failed R blogs which tried to do too many things:

- [www.visibledata.co.uk](www.visibledata.co.uk) was designed as the company website for my R consultancy work. It was abandoned in favour of...

- [www.findingyourway.io](www.visibledata.co.uk) was to accompany a book project I abandoned. It has lots of wonderfully customised (Bootstrap flavoured) CSS.

But these days I do my consultancy through the awesome [R for The Rest of Us](https://rfortherestofus.com/) team. That's also where my [fancy markety blogposts](https://rfortherestofus.com/2022/03/heatmaps/).

This is going to be the home for #30DayChartChallenge, #TidyTuesday and other things.

To prevent this from going the way of the abandoned projects, here are my rules:

- All custom CSS needs to be declared here.

- All {distill} modifications need to be declared here.

## Customisations

### Showing recent posts on the home page

The home page shows a list of all blogposts, which is achieved by adding this to the `index.Rmd` file:

```{verbatim, echo=TRUE}
---
title: "Posts"
listing: posts
site: distill::distill_website
---
```

To place additional content about the posts I make use of `<d-byline></d-byline>` which forces the content below into a comfortable position.

## Tutorials used

https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/
